### ISSUE TITLE
Stage 5 Linux Package fails to build due to an zstd allocation error

### ISSUE THREAD

**Issue by TechdudeGames** [rxrbln/t2sde#67]
Salutations,
While attempting to build T2 for i486, I noticed that the stage 5 Linux package would fail to build. Upon looking at the build log, it wasn't immediately obvious what the problem was since it would build for quite some time and the error was not near the end. 

My build environment has changed since my last issue. I am running my own build of T2 for the Intel Pentium III, running underneath QEMU on a different rig. My specs are as follows:
CPU: Intel i5 8400
Ram: 16 GB DDR4 2666
Host OS: Ubuntu 20.04

For my QEMU configuration, I have given T2 4GB and for my CPU I have it set to a Pentium III running with 5 of my 6 cores. 

After searching for what caused the problem, I located this section in the error log:
>   ZSTD22  arch/x86/boot/compressed/vmlinux.bin.zst
zstd: error 11 : Allocation error : not enough memory 
make[2]: *** [arch/x86/boot/compressed/Makefile:136: arch/x86/boot/compressed/vmlinux.bin.zst] Error 11
make[2]: *** Deleting file 'arch/x86/boot/compressed/vmlinux.bin.zst'
make[2]: *** Waiting for unfinished jobs....

Like the error states, I zstd is trying to allocate a memory buffer for vmlinux but fails to do so. It is possible that part of the issue has to do with the fact that the kernel is being built in the chroot environment, meaning all of the programs associated with the build are capped by the amount of memory a 32 bit machine can utilize. I have also tried building with only one core allocated to the VM, but the error persisted.

I have bypassed this issue before by modifying T2 to use LZMA instead of zstd, since lzma compresses vmlinux without running out of memory. It was how I build T2 the first time on my 2x Xeon X5672 64 bit machine.

[ERROR-LOG.txt](https://github.com/rxrbln/t2sde/files/7777767/ERROR-LOG.txt)
[486Conf.zip](https://github.com/rxrbln/t2sde/files/7777769/486Conf.zip)

**Comment by rxrbln** [comment]
Hi, you simply don't have enough memory for zest compression. I recently (IIRC yesterday) change the compression level for 32-bit architecture builds to a lower level, so that those lower end CPUs require less memory, especially to install. This does not change 64-bit builds though which we certainly prefer highly compressed. I suggest simply allocated more RAM to the VM. Otherwise you could also edit the level in scripts/Build-Target to a lower level IMHO making this a config option would be overkill though, ...
